---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: podinfo-rc
  namespace: stg
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:stg-*
spec:
  releaseName: podinfo-rc
  chart:
    git: git@github.com:budi-khoirudin/helm-operator-get-started
    path: charts/podinfo
    ref: master
  values:
    image:
      repository: malaikat14/podinfo
      tag: stg-fk6afkgj
    replicaCount: 2
    hpa:
      enabled: true
      maxReplicas: 2
      cpu: 50
      memory: 128Mi
